#!/bin/bash
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=1000M
#SBATCH --time=01:00:00
#SBATCH --job-name=fastqc
#SBATCH --mail-user=¨bella.mattam@students.unibe.ch
#SBATCH --mail-type=begin,end
#SBATCH --partition=pcourse80
#SBATCH --output=/data/courses/rnaseq/toxoplasma_de/bmattam/output_fastqc.o
#SBATCH --error=/data/courses/rnaseq/toxoplasma_de/bmattam/error_fastqc.e
#SBATCH --array=0-31

module add UHTS/Quality_control/fastqc/0.11.7

INPUT_FILES=(/data/courses/rnaseq/toxoplasma_de/reads/*)
OUTPUT_DIR=/data/courses/rnaseq/toxoplasma_de/bmattam/fastqc/

mkdir $OUTPUT_DIR
fastqc --outdir=$OUTPUT_DIR ${INPUT_FILES[$SLURM_ARRAY_TASK_ID]}
