#!/bin/bash
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=8000M
#SBATCH --time=03:00:00
#SBATCH --job-name=index_hisat2
#SBATCH --mail-user=bella.mattam@students.unibe.ch
#SBATCH --mail-type=begin,end
#SBATCH --partition=pcourse80
#SBATCH --output=/data/courses/rnaseq/toxoplasma_de/bmattam/index_hisat2/outputs_errors/output_%j.o
#SBATCH --error=/data/courses/rnaseq/toxoplasma_de/bmattam/index_hisat2/outputs_errors/error_%j.e

module add UHTS/Aligner/hisat/2.2.1

INPUT_DIR=/data/courses/rnaseq/toxoplasma_de/genome/Mus_musculus.GRCm38.dna.primary_assembly.fa
OUTPUT_DIR=/data/courses/rnaseq/toxoplasma_de/bmattam/index_hisat2/Mus_musculus.GRCm38


hisat2-build -p 1 ${INPUT_DIR} ${OUTPUT_DIR}
